AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: dima

Globals:
  Api:
    OpenApiVersion: 3.0.2

Parameters:
  ApplicationName:
    Description: Application name
    Type: String
    Default: dima
  SashaTableName:
    Description: DynamoDB table name of sasha
    Type: String
  APIDomainName:
    Description: API domain name
    Type: String
  CertificateArn:
    Description: ACM certificate arn
    Type: String
  Route53HostedZoneId:
    Description: Route53 hostzone id for the APIDomainName
    Type: String
  # DaysToRetainLogs:
  #   Description: days to retain logs in CloudWatch
  #   Type: Number
  #   Default: 30

Resources:
  RestAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Ref ApplicationName
      StageName: api
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: api/openapi.yml
      Domain:
        BasePath: /
        CertificateArn: !Ref CertificateArn
        DomainName: !Ref APIDomainName
        EndpointConfiguration: EDGE
        Route53:
          HostedZoneId: !Ref Route53HostedZoneId

  Function:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Ref ApplicationName
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2023
      MemorySize: 128
      Timeout: 30
      Tracing: PassThrough
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref SashaTableName
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref RestAPI
        Matches:
          Type: Api
          Properties:
            Path: /matches
            Method: GET
            RestApiId: !Ref RestAPI

  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Function}

Outputs:
  FunctionArn:
    Value: !GetAtt Function.Arn
  FunctionName:
    Value: !Ref Function
  CustomEndpointURL:
    Value: !Sub "https://${APIDomainName}/"
  EndpointURL:
    Value: !Sub "https://${RestAPI}.execute-api.${AWS::Region}.${AWS::URLSuffix}/api/"
  RestAPIId:
    Value: !Ref RestAPI
