on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/*"
      - "**.md"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true
      - name: Require Variables
        run: |
          SASHA_TABLE_NAME=` \
            aws cloudformation describe-stacks --stack-name sasha \
          | jq -r '.Stacks[].Outputs[] | select(.OutputKey == "VlrMatchesTableName"  ) | .OutputValue'`
          echo "SASHA_TABLE_NAME=$SASHA_TABLE_NAME" >> $GITHUB_ENV
      - name: Prepare SAM parameters
        env:
          APPLICATION_NAME: ${{ env.APPLICATION_NAME }}
          SASHA_TABLE_NAME: ${{ env.SASHA_TABLE_NAME }}
          API_DOMAIN_NAME: ${{ secrets.API_DOMAIN_NAME }}
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
          ROUTE53_HOSTED_ZONE_ID: ${{ secrets.ROUTE53_HOSTED_ZONE_ID }}
          DAYS_TO_RETAIN_LOGS: ${{ vars.DAYS_TO_RETAIN_LOGS }}
        run: |
          tee params.json << EOF
          { 
            "ApplicationName": "${APPLICATION_NAME}",
            "SashaTableName": "${SASHA_TABLE_NAME}",
            "APIDomainName": "${API_DOMAIN_NAME}",
            "CertificateArn": "${CERTIFICATE_ARN}",
            "Route53HostedZoneId": "${ROUTE53_HOSTED_ZONE_ID}",
            "DaysToRetainLogs": "${DAYS_TO_RETAIN_LOGS}"
          }
          EOF
      - name: Build SAM packages
        run: sam build
      - name: Deploy SAM application
        env:
          BUCKET_NAME: ${{ secrets.PROVISIONING_BUCKET_NAME }}
          REGION: ${{ secrets.AWS_REGION }}
          STACK_NAME: ${{ vars.STACK_NAME }}
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name $STACK_NAME \
            --s3-bucket $BUCKET_NAME \
            --s3-prefix $STACK_NAME \
            --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
            --region $REGION \
            --force-upload \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides "$(jq -j 'to_entries[] | "\(.key)='\\\"'\(.value)'\\\"''\ '"' params.json)"
